/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import NUHealthCare.Account.Account;
import NUHealthCare.DB4OUtil.DB4OUtil;
import NUHealthCare.Ecosystem;
import NUHealthCare.Enterprise.Enterprise;
import NUHealthCare.NetworkSystem.NetworkSystem;
import NUHealthCare.Org.Org;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;





/**
 *
 * @author Rishabh,Uday,Aditi
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    private final Ecosystem ecosystem;
    private final DB4OUtil db4oUtil = DB4OUtil.getInstance();

    public LandingPage() {
        initComponents();
        ecosystem = db4oUtil.retrieveSystem();
        
        Image icon = new ImageIcon(this.getClass().getResource("/LandIcon.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        rightJPanel = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        JlblUserName = new javax.swing.JLabel();
        JlblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        leftJPanel = new javax.swing.JPanel();
        LandingImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(1200);

        rightJPanel.setBackground(new java.awt.Color(153, 0, 0));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        JlblUserName.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        JlblUserName.setForeground(new java.awt.Color(255, 255, 255));
        JlblUserName.setText("User Name");

        JlblPassword.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        JlblPassword.setForeground(new java.awt.Color(255, 255, 255));
        JlblPassword.setText("Password");

        lblUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Assets/codicon_account.png"))); // NOI18N

        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Assets/carbon_password.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Assets/NU_logo.png"))); // NOI18N

        javax.swing.GroupLayout rightJPanelLayout = new javax.swing.GroupLayout(rightJPanel);
        rightJPanel.setLayout(rightJPanelLayout);
        rightJPanelLayout.setHorizontalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJPanelLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(rightJPanelLayout.createSequentialGroup()
                            .addComponent(lblUserName)
                            .addGap(7, 7, 7)
                            .addComponent(JlblUserName)))
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPassword)
                        .addGap(7, 7, 7)
                        .addComponent(JlblPassword)))
                .addGap(240, 240, 240))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rightJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogin, btnLogout, txtUserName});

        rightJPanelLayout.setVerticalGroup(
            rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(JlblUserName))
                    .addComponent(lblUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(JlblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(rightJPanel);

        leftJPanel.setLayout(new java.awt.CardLayout());

        LandingImg.setBackground(new java.awt.Color(0, 0, 0));
        LandingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Assets/Best-Black-1920x1080-Photos.jpg"))); // NOI18N
        leftJPanel.add(LandingImg, "card2");

        jSplitPane1.setLeftComponent(leftJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        // Get username
        String username = txtUserName.getText();

        // Get Password
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        Account account = ecosystem.getUserAccountDirectory().authUser(username, password);

        Enterprise inEnterprise = null;
        Org inOrg = null;

        if (account == null) {
            for (NetworkSystem ns : ecosystem.getNetworkSystems()) {
                for (Enterprise e : ns.getEnterpriseDirectory().getEnterpriseList()) {
                    account = e.getUserAccountDirectory().authUser(username, password);
                    if (account == null) {
                        for (Org org : e.getOrgDirectory().getOrganizations()) {
                            account = org.getUserAccountDirectory().authUser(username, password);
                            if (account != null) {
                                inEnterprise = e;
                                inOrg = org;
                                break;
                            }
                        }
                    } else {
                        inEnterprise = e;
                        break;
                    }
                    if (inOrg != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }
        }

        // Set UI warnings
        if (account == null) {
            txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Invalid credentials!");
            return;
        } else {
            txtUserName.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            CardLayout layout = (CardLayout) leftJPanel.getLayout();
            leftJPanel.add("workArea", account.getRole().createWorkArea(leftJPanel, account, inOrg, inEnterprise, ecosystem));
            layout.next(leftJPanel);
        }

        // Disable features after successful login
        btnLogin.setEnabled(false);
        btnLogout.setEnabled(true);
        txtUserName.setEnabled(false);
        txtPassword.setEnabled(false);
  }//GEN-LAST:event_btnLoginActionPerformed

  private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        btnLogin.setEnabled(true);
        btnLogout.setEnabled(false);
        txtUserName.setEnabled(true);
        txtPassword.setEnabled(true);

        txtUserName.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtPassword.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        txtUserName.setText("");
        txtPassword.setText("");

        leftJPanel.removeAll();
        JPanel blankJPanel = new JPanel();
        leftJPanel.add(blankJPanel);

        CardLayout layout = (CardLayout) leftJPanel.getLayout();
        layout.next(leftJPanel);
        LandingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Assets/Best-Black-1920x1080-Photos.jpg")));
        LandingImg.setMaximumSize(new java.awt.Dimension(1300, 750));
        LandingImg.setMinimumSize(new java.awt.Dimension(1300, 750));
        blankJPanel.add(LandingImg, "card2");
        LandingImg.getAccessibleContext().setAccessibleName("LandingImg");

        db4oUtil.storeSystem(ecosystem);
  }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JlblPassword;
    public javax.swing.JLabel JlblUserName;
    private javax.swing.JLabel LandingImg;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
