/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PatientRole;

import NUHealthCare.Account.Account;
import NUHealthCare.Ecosystem;
import NUHealthCare.Enterprise.HealthCareEnterprise;
import NUHealthCare.Enterprise.Enterprise;
import NUHealthCare.Map.MapViewer;
import NUHealthCare.NetworkSystem.NetworkSystem;
import UI.PharmacyManager.SendEmailJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishabh,Uday,Aditi
 */
public class PatientVisitPlan extends javax.swing.JPanel {

    /**
     * Creates new form PatientVisitPlan
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Account account;
    private Ecosystem ecosystem;
    
    public PatientVisitPlan(JPanel userProcessContainer, Account account, Enterprise enterprise,Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.ecosystem = business;
        patientId.setText(account.getCustomer().getPatientID());
        patientName.setText(account.getCustomer().getPatientFName()+" "+account.getCustomer().getPatientLName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        lblPatientId = new javax.swing.JLabel();
        patientId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnMap = new javax.swing.JButton();
        btnDir = new javax.swing.JButton();
        btnEmail = new javax.swing.JButton();
        btnWeb = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        workRequestJTable.setBackground(new java.awt.Color(204, 204, 204));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hospital", "Network", "Address", "Email", "WebSite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        lblPatientId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPatientId.setText("Patient Id:");

        patientId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patientId.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Patient Name:");

        patientName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patientName.setForeground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnMap.setBackground(new java.awt.Color(153, 0, 0));
        btnMap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMap.setForeground(new java.awt.Color(255, 255, 255));
        btnMap.setText("View on Map");
        btnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapActionPerformed(evt);
            }
        });

        btnDir.setBackground(new java.awt.Color(153, 0, 0));
        btnDir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDir.setForeground(new java.awt.Color(255, 255, 255));
        btnDir.setText("View Directions");
        btnDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirActionPerformed(evt);
            }
        });

        btnEmail.setBackground(new java.awt.Color(153, 0, 0));
        btnEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmail.setForeground(new java.awt.Color(255, 255, 255));
        btnEmail.setText("Send Email Query");
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });

        btnWeb.setBackground(new java.awt.Color(153, 0, 0));
        btnWeb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnWeb.setForeground(new java.awt.Color(255, 255, 255));
        btnWeb.setText("View Website");
        btnWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Plan Your Next Visit Portal ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(806, 1120, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMap)
                            .addComponent(btnEmail)
                            .addComponent(btnDir)
                            .addComponent(btnWeb)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientId)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientId, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblTitle)
                        .addGap(83, 83, 83)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDir, btnEmail, btnMap, btnWeb});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(82, 82, 82)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblPatientId)))
                        .addGap(18, 18, 18)
                        .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnMap)
                .addGap(18, 18, 18)
                .addComponent(btnDir)
                .addGap(18, 18, 18)
                .addComponent(btnEmail)
                .addGap(18, 18, 18)
                .addComponent(btnWeb)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDir, btnEmail, btnMap, btnWeb});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      userProcessContainer.remove(this);
      Component[] componentArray = userProcessContainer.getComponents();
      Component component = componentArray[componentArray.length - 1];
      PatientWorkArea patientWA = (PatientWorkArea) component;
      patientWA.populateTable();
      patientWA.populateInsuranceTable();
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapActionPerformed
      // TODO add your handling code here:
      int selectedRow = workRequestJTable.getSelectedRow();
      if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row first");
        return;
      }
      String location = workRequestJTable.getValueAt(selectedRow, 2).toString();
      if (location.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Select a row first");
      } else {
        SwingUtilities.invokeLater(new Runnable() {
          @Override
          public void run() {
            MapViewer browser = new MapViewer();
            browser.setVisible(true);
            browser.loadURL("https://www.google.com/maps/search/?api=1&query=" + location.trim());
          }
        });
      }
    }//GEN-LAST:event_btnMapActionPerformed

    private void btnDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirActionPerformed
      // TODO add your handling code here:
      int selectedRow = workRequestJTable.getSelectedRow();
      if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row first");
        return;
      }
      String location = workRequestJTable.getValueAt(selectedRow, 2).toString();
      if (location.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Select a row first");
      } else {
        SwingUtilities.invokeLater(new Runnable() {
          @Override
          public void run() {
            MapViewer browser = new MapViewer();
            browser.setVisible(true);
            browser.loadURL("https://www.google.com/maps/dir/?api=1&destination=" + location.trim());
          }
        });
      }
    }//GEN-LAST:event_btnDirActionPerformed

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailActionPerformed
        // TODO add your handling code here:
      int selectedRow = workRequestJTable.getSelectedRow();
      String to = "";
      if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row first");
        return;
      } else {
        to = workRequestJTable.getValueAt(selectedRow, 3).toString();
        SendEmailJPanel emailJPanel = new SendEmailJPanel(userProcessContainer, to, "Customer");
        userProcessContainer.add("emailJPanel", emailJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      }
    }//GEN-LAST:event_btnEmailActionPerformed

    private void btnWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebActionPerformed
      // TODO add your handling code here:
      int selectedRow = workRequestJTable.getSelectedRow();
      if (selectedRow < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row first");
        return;
      }
      String location = workRequestJTable.getValueAt(selectedRow, 4).toString();
      if (location.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Select a row first");
      } else {
        SwingUtilities.invokeLater(new Runnable() {
          @Override
          public void run() {
            MapViewer browser = new MapViewer();
            browser.setVisible(true);
            browser.loadURL(location.trim());
          }
        });
      }
    }//GEN-LAST:event_btnWebActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDir;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnMap;
    private javax.swing.JButton btnWeb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel patientId;
    private javax.swing.JLabel patientName;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

  public void populateTable() {
    DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
    model.setRowCount(0);
    for (NetworkSystem ns : ecosystem.getNetworkSystems()) {
      for (Enterprise e : ns.getEnterpriseDirectory().
          getEnterpriseList()) {
        if ((e instanceof HealthCareEnterprise) && (ns.getZipcode() == e.getZipcode())) {
          String website = "https://www.google.com";
          Object[] row = new Object[5];
          row[0] = e.getOrgName();
          row[1] = ns.getName();
          row[2] = e.getAddress();
          row[3] = e.getEmail();
          row[4] = website;
          model.addRow(row);
        }
      }

    }
  }
}
