/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HealthcareAccountant;

import NUHealthCare.Account.Account;
import NUHealthCare.Ecosystem;
import NUHealthCare.Enterprise.Enterprise;
import NUHealthCare.Enterprise.InsuranceCompanyEnterprise;
import NUHealthCare.Insurance.Insurance;
import NUHealthCare.InsuranceCustomer.InsuranceCustomer;
import NUHealthCare.JobQueue.AccountsBillingJob;
import NUHealthCare.JobQueue.InsuranceJob;
import NUHealthCare.Map.SMS;
import NUHealthCare.Map.SendEmail;
import NUHealthCare.NetworkSystem.NetworkSystem;
import NUHealthCare.Org.AccountantOrg;
import NUHealthCare.Org.InsuranceAgentOrg;
import NUHealthCare.Org.Org;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rishabh,Uday,Aditi
 */
public class AccountantProcessRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Account account;
    private Enterprise enterprise;
    private AccountantOrg accountantOrg;
    private AccountsBillingJob accountBillingJob;
    private Ecosystem ecosystem;
    private double payableAmount;

    /**
     * Creates new form AccountantJPanel
     */
    public AccountantProcessRequestJPanel(JPanel userProcessContainer, Account account, AccountsBillingJob request, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.accountantOrg = accountantOrg;
        this.accountBillingJob = request;
        this.ecosystem = ecosystem;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSendRequestForInsurance = new javax.swing.JButton();
        txtSSN = new javax.swing.JTextField();
        txtInsurancePolicyName = new javax.swing.JTextField();
        txtPayableAmount = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtBillAmount = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPolicyNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInsuranceClaimAmount = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCollectCash = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Process Billing Request Area");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SSN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("FirstName");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("LastName");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Bill Amount");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Insurance Policy Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Payable Amount");

        btnSendRequestForInsurance.setBackground(new java.awt.Color(153, 0, 0));
        btnSendRequestForInsurance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSendRequestForInsurance.setForeground(new java.awt.Color(255, 255, 255));
        btnSendRequestForInsurance.setText("Receive Amount / Send request for Insurance Claim");
        btnSendRequestForInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestForInsuranceActionPerformed(evt);
            }
        });

        txtSSN.setEditable(false);

        txtInsurancePolicyName.setEditable(false);

        txtPayableAmount.setEditable(false);

        txtFirstName.setEditable(false);

        txtBillAmount.setEditable(false);

        txtLastName.setEditable(false);

        txtPolicyNumber.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Policy Number");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Insurance Claim Amount");

        txtInsuranceClaimAmount.setEditable(false);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCollectCash.setBackground(new java.awt.Color(153, 0, 0));
        btnCollectCash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCollectCash.setForeground(new java.awt.Color(255, 255, 255));
        btnCollectCash.setText("Receive complete amount from patient");
        btnCollectCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectCashActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Assets/Invoice.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel8)
                                .addGap(52, 52, 52)
                                .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addGap(52, 52, 52)
                                .addComponent(txtInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel4)
                                .addGap(52, 52, 52)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52)
                                .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(52, 52, 52)
                                .addComponent(txtInsuranceClaimAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52)
                                .addComponent(txtPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnCollectCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSendRequestForInsurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(17, 17, 17))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCollectCash, btnSendRequestForInsurance});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addComponent(txtPolicyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6))
                            .addComponent(txtInsurancePolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9))
                            .addComponent(txtInsuranceClaimAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(txtPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnSendRequestForInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCollectCash, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCollectCash, btnSendRequestForInsurance});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestForInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestForInsuranceActionPerformed
        String policyNumber = accountBillingJob.getPatient().getInsuranceCustomer().getInsurancePlanNumber();
        String ssn = accountBillingJob.getPatient().getSSN();
        String policyName = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getPlanName();
        String insuranceCompany = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompany();
        String email = accountBillingJob.getPatient().getPatientEmail();
        String phone = accountBillingJob.getPatient().getPhoneNumber();
        double claimAmount = Double.parseDouble(txtInsuranceClaimAmount.getText());
        double billAmount = accountBillingJob.getBillingAmt();
        String sub = "Your Medical Bill is Processed";

        Insurance insurance = new Insurance(policyName, insuranceCompany, claimAmount);
        insurance.setReimbursement(accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getReimbursement());

        InsuranceCustomer insuranceCustomer = new InsuranceCustomer(insurance, policyNumber);
        insuranceCustomer.setCustomerFName(txtFirstName.getText().trim());
        insuranceCustomer.setCustomerLName((txtLastName.getText().trim()));

        InsuranceJob insuranceWorkRequest = new InsuranceJob();
        insuranceWorkRequest.setInsuranceCompany(insuranceCompany);
        insuranceWorkRequest.setPolicyNumber(policyNumber);
        insuranceWorkRequest.setPolicyName(policyName);
        insuranceWorkRequest.setSsn(ssn);
        insuranceWorkRequest.setClaimAmount(claimAmount);
        insuranceWorkRequest.setBillAmount(billAmount);
        insuranceWorkRequest.setHealthCenter(enterprise.getOrgName());

        insuranceWorkRequest.setSender(account);
        insuranceWorkRequest.setStatus("Sent");
        insuranceWorkRequest.setInsuranceCustomer(insuranceCustomer);
        insuranceWorkRequest.setCustomerEmail(email);
        insuranceWorkRequest.setCustomerPhone(phone);

        Org org = null;
        InsuranceCompanyEnterprise matchedInsuranceCompany = null;

        List<NetworkSystem> networks = ecosystem.getNetworkSystems();
        for (NetworkSystem network : networks) {
            List<Enterprise> enterprises = network.getEnterpriseDirectory().getEnterpriseList();
            for (Enterprise enterprise : enterprises) {
                if (enterprise.getOrgName().equalsIgnoreCase(accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompany())) {
                    matchedInsuranceCompany = (InsuranceCompanyEnterprise) enterprise;
                }
            }
        }

        for (Org organization : matchedInsuranceCompany.getOrgDirectory().getOrganizations()) {
            if (organization instanceof InsuranceAgentOrg) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getJobQueue().getJobRequestList().add(insuranceWorkRequest);
            account.getJobQueue().getJobRequestList().add(insuranceWorkRequest);
            accountBillingJob.setStatus("Patient Transaction Completed");
            accountBillingJob.getPatient().setIsTreatmentDone(true);
            accountBillingJob.getVisitRequest().setIsComplete(true);
            try {
                SendEmail.send(accountBillingJob.getPatient().getPatientEmail(), "\nHi " + accountBillingJob.getPatient().getPatientFName() + "," + "\n\nYour Medical bill of amount: " + accountBillingJob.getBillingAmt()
                        + " is processed" + "\n\n\nThanks\n" + enterprise.getOrgName(), sub);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Email Sent");
                System.out.println(ex.getMessage());
            }
            //Send SMS
            try {
                SMS.SendSMS("+18573138300", "Hi " + accountBillingJob.getPatient().getPatientFName() + "," + "\nYour Medical Bill of amount: " + accountBillingJob.getBillingAmt()
                        + " is processed" + "\n\nThanks,\n" + enterprise.getOrgName());
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            //Send SMS end
            JOptionPane.showMessageDialog(null, "Money received from patient: " + payableAmount + ". Insurance Claim Request Raised Successfully for amount:" + claimAmount);

            btnSendRequestForInsurance.setEnabled(false);
        }
    }//GEN-LAST:event_btnSendRequestForInsuranceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcessMedicalBillsJPanel pmbjp = (ProcessMedicalBillsJPanel) component;
        pmbjp.populateTable();
        pmbjp.populateInsuranceClaimTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCollectCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectCashActionPerformed
        String sub = "Your Medical Bill is Processed";
        accountBillingJob.setStatus("Patient Transaction Completed");
        accountBillingJob.getPatient().setIsTreatmentDone(true);
        accountBillingJob.getVisitRequest().setIsComplete(true);
        try {
            SendEmail.send(accountBillingJob.getPatient().getPatientEmail(), "\nHi " + accountBillingJob.getPatient().getPatientFName() + "," + "\n\nYour Medical bill of amount: " + accountBillingJob.getBillingAmt()
                    + " is processed" + "\n\n\nThanks\n" + enterprise.getOrgName(), sub);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Email Sent");
            System.out.println(ex.getMessage());
        }
        //Send SMS
        try {
            SMS.SendSMS("+18573138300", "Hi " + accountBillingJob.getPatient().getPatientFName() + "," + "\nYour Medical Bill of amount: " + accountBillingJob.getBillingAmt()
                    + " is processed" + "\n\nThanks,\n" + enterprise.getOrgName());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        //Send SMS end
        JOptionPane.showMessageDialog(null, "Amount received from Patient");
        btnCollectCash.setEnabled(false);
    }//GEN-LAST:event_btnCollectCashActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCollectCash;
    private javax.swing.JButton btnSendRequestForInsurance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBillAmount;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtInsuranceClaimAmount;
    private javax.swing.JTextField txtInsurancePolicyName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPayableAmount;
    private javax.swing.JTextField txtPolicyNumber;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
    private void populate() {
        String policyNumber = accountBillingJob.getPatient().getInsuranceCustomer().getInsurancePlanNumber();
        double coverage = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getReimbursement();
        double billAmount = accountBillingJob.getBillingAmt();
        String ssn = accountBillingJob.getPatient().getSSN();
        String policyName = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getPlanName();
        String insuranceCompany = accountBillingJob.getPatient().getInsuranceCustomer().getInsurance().getInsuranceCompany();
        double claimAmount = (coverage * billAmount) / 100;
        payableAmount = billAmount - claimAmount;

        txtPolicyNumber.setText(policyNumber);
        txtSSN.setText(ssn);
        txtFirstName.setText(accountBillingJob.getPatient().getPatientFName());
        txtLastName.setText(accountBillingJob.getPatient().getPatientLName());
        txtBillAmount.setText(String.valueOf(billAmount));
        txtInsurancePolicyName.setText(policyName);
        txtInsuranceClaimAmount.setText(String.valueOf(claimAmount));
        txtPayableAmount.setText(String.valueOf(payableAmount));

        if (claimAmount > 0) {
            btnSendRequestForInsurance.setEnabled(true);
            btnCollectCash.setEnabled(false);
        } else {
            btnCollectCash.setEnabled(true);
            btnSendRequestForInsurance.setEnabled(false);
        }

    }

}
